AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Rename mobile devices to their serial number after enrollment.

Parameters:

  JamfProUrl:
    Type: String
    Description: https://example.jamfcloud.com (No trailing slash)

  JamfConnectionArn:
    Type: String
    Description: The connection ARN from the outputs of the base resources stack.

  WebhooksEventBusName:
    Type: String
    Description: The event bus name from the outputs of the base resources stack.

Resources:

  RenameMobileDevices:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${AWS::StackName}-RenameMobileDevices
      DefinitionUri: ./rename_mobile_devices.asl.yaml
      DefinitionSubstitutions:
        JamfProUrl: !Ref JamfProUrl
        JamfConnectionArn: !Ref JamfConnectionArn
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - events:RetrieveConnectionCredentials
            Resource: !Ref JamfConnectionArn
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: arn:aws:secretsmanager:*:*:secret:events!connection/*
          - Effect: Allow
            Action: states:InvokeHTTPEndpoint
            Resource: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-RenameMobileDevices"
            Condition:
              StringEquals:
                states:HTTPMethod: GET
              StringLike:
                states:HTTPEndpoint: !Sub "${JamfProUrl}/api/v2/mobile-devices/*"
          - Effect: Allow
            Action: states:InvokeHTTPEndpoint
            Resource: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-RenameMobileDevices"
            Condition:
              StringEquals:
                states:HTTPMethod: POST
              StringLike:
                states:HTTPEndpoint: !Sub "${JamfProUrl}/api/preview/mdm/commands"
      Events:
        Enrolled:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref WebhooksEventBusName
            Pattern:
              source:
                - Webhooks API
              detail-type:
                - Jamf Pro Webhook
              detail:
                webhook:
                  webhookEvent:
                    - MobileDeviceEnrolled
