AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Rename mobile devices to their serial number after enrollment.

Parameters:

  JamfProUrl:
    Type: String
    Description: https://example.jamfcloud.com (No trailing slash)

  JamfConnectionArn:
    Type: String
    Description: The connection ARN from the outputs of the base resources stack.

  WebhooksEventBusName:
    Type: String
    Description: The event bus name from the outputs of the base resources stack.

Resources:

  RenameMobileDevices:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${AWS::StackName}-RenameMobileDevices
      Type: EXPRESS
      DefinitionSubstitutions:
        JamfProUrl: !Ref JamfProUrl
        JamfConnectionArn: !Ref JamfConnectionArn
#      DefinitionUri: ./rename_mobile_devices.asl.yaml
      Definition:
        Comment: Rename mobile devices to their serial numbers after enrollment.
        StartAt: Webhook has Management ID?

        States:

          Webhook has Management ID?:
            Type: Choice
            Choices:
              - Variable: $.event.managementId
                IsPresent: true
                Next: Extract Management ID
                Comment: Management ID Present
            Default: Get Management ID

          Extract Management ID:
            Type: Pass
            Next: Rename Mobile Device
            Result:
              value: $.event.managementId
            ResultPath: $.managementId

          Get Management ID:
            Type: Task
            Resource: arn:aws:states:::http:invoke
            Parameters:
              Method: GET
              ApiEndpoint.$: States.Format('${JamfProUrl}/api/v2/mobile-devices/{}', $.event.jssID)
              Authentication:
                ConnectionArn: ${JamfConnectionArn}
              QueryParameters:
                section: GENERAL
            Retry:
              - ErrorEquals:
                  - States.ALL
                BackoffRate: 2
                IntervalSeconds: 1
                MaxAttempts: 3
                JitterStrategy: FULL
            Next: Rename Mobile Device
            ResultSelector:
              value: $.general.managementId
            ResultPath: $.managementId

          Rename Mobile Device:
            Type: Task
            Resource: arn:aws:states:::http:invoke
            Parameters:
              ApiEndpoint: ${JamfProUrl}/api/preview/mdm/commands
              Method: POST
              Authentication:
                ConnectionArn: ${JamfConnectionArn}
              RequestBody:
                commandData:
                  commandType: SETTINGS
                  deviceName.$: $.event.serialNumber
                clientData:
                  - managementId.$: $.managementId.value
            Retry:
              - ErrorEquals:
                  - States.ALL
                BackoffRate: 2
                IntervalSeconds: 1
                MaxAttempts: 3
                JitterStrategy: FULL
            End: true
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - events:RetrieveConnectionCredentials
            Resource: !Ref JamfConnectionArn
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: arn:aws:secretsmanager:*:*:secret:events!connection/*
          - Effect: Allow
            Action: states:InvokeHTTPEndpoint
            Resource: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-RenameMobileDevices"
            Condition:
              StringEquals:
                states:HTTPMethod: GET
              StringLike:
                states:HTTPEndpoint: !Sub "${JamfProUrl}/api/v2/mobile-devices/*"
          - Effect: Allow
            Action: states:InvokeHTTPEndpoint
            Resource: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-RenameMobileDevices"
            Condition:
              StringEquals:
                states:HTTPMethod: POST
              StringLike:
                states:HTTPEndpoint: !Sub "${JamfProUrl}/api/preview/mdm/commands"
      Events:
        Enrolled:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref WebhooksEventBusName
            Pattern:
              source:
                - Webhooks API
              detail-type:
                - Jamf Pro Webhook
              detail:
                webhook:
                  webhookEvent:
                    - MobileDeviceEnrolled
