AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Redeploy the Jamf Management Framework to computers that are added to a group.

Parameters:

  JamfProUrl:
    Type: String
    Description: https://example.jamfcloud.com (No trailing slash)

  JamfConnectionArn:
    Type: String
    Description: The connection ARN from the outputs of the base resources stack.

  WebhooksEventBusName:
    Type: String
    Description: The event bus name from the outputs of the base resources stack.

  ComputerGroupId:
    Type: Number
    Description: The ID of the computer group to listen for.

Resources:

  RedeployManagementFramework:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${AWS::StackName}-RedeployManagementFramework
      Type: EXPRESS
      DefinitionSubstitutions:
        JamfProUrl: !Ref JamfProUrl
        JamfConnectionArn: !Ref JamfConnectionArn
#      DefinitionUri: ./redeploy_management_framework.asl.yaml
      Definition:
        Comment: Redeploy the management framework to computers when they are added to a group.
        StartAt: Redeploy Management Framework to All Devices

        States:

          Redeploy Management Framework to All Devices:
            Type: Map
            End: true
            MaxConcurrency: 5
            ItemsPath: $.event.groupAddedDevicesIds
            ItemSelector:
              id.$: $
            ItemProcessor:
              ProcessorConfig:
                Mode: INLINE
              StartAt: Redeploy Management Framework
              States:

                Redeploy Management Framework:
                  Type: Task
                  Resource: arn:aws:states:::http:invoke
                  Parameters:
                    ApiEndpoint.$: States.Format('${JamfProUrl}/api/v1/jamf-management-framework/redeploy/{}', $.id)
                    Method: POST
                    Authentication:
                      ConnectionArn: ${JamfConnectionArn}
                  Retry:
                    - ErrorEquals:
                        - States.ALL
                      BackoffRate: 2
                      IntervalSeconds: 1
                      MaxAttempts: 3
                      JitterStrategy: FULL
                  Catch:
                    - ErrorEquals:
                        - States.ALL
                      Comment: On Error
                      Next: Error Sending Command
                      ResultPath: $.error
                  End: true

                Error Sending Command:
                  Type: Pass
                  End: true
                  Comment: Comment
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - events:RetrieveConnectionCredentials
            Resource: !Ref JamfConnectionArn
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: arn:aws:secretsmanager:*:*:secret:events!connection/*
          - Effect: Allow
            Action: states:InvokeHTTPEndpoint
            Resource: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-RedeployManagementFramework"
            Condition:
              StringEquals:
                states:HTTPMethod: POST
              StringLike:
                states:HTTPEndpoint: !Sub "${JamfProUrl}/api/v1/jamf-management-framework/redeploy/*"
      Events:
        Group:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref WebhooksEventBusName
            Pattern:
              source:
                - Webhooks API
              detail-type:
                - Jamf Pro Webhook
              detail:
                id:
                  - !Ref ComputerGroupId
                webhook:
                  webhookEvent:
                    - SmartGroupComputerMembershipChange
